### ISSUE TITLE
Failed to build documents tree: failed to mirror was not ok

### ISSUE THREAD

**Issue by Azeirah** [ddvk/rmapi#6]
```
Trace: 2024/10/30 17:19:06 main.go:72: failed to mirror was not ok: cant parse line '', wrong number of fields 0
ERROR: 2024/10/30 17:19:06 main.go:79: failed to build documents tree, last error: failed to mirror was not ok: cant parse line '', wrong number of fields 0
```

https://github.com/ddvk/rmapi/blob/a0c746f65c5d4af63a3b9c6576b709e24fc98642/api/sync15/apictx.go#L49

https://github.com/ddvk/rmapi/blob/a0c746f65c5d4af63a3b9c6576b709e24fc98642/api/sync15/tree.go#L171

https://github.com/ddvk/rmapi/blob/a0c746f65c5d4af63a3b9c6576b709e24fc98642/api/sync15/tree.go#L95

Not sure what I can provide for further context. The trace doesn't contain the content it failed to mirror on.

**Comment by Azeirah** [comment]
Looks like a line is unexpectedly empty. I'm not super familiar with rmapi myself

**Comment by ddvk** [comment]
you can run with logging e.g. `RMAPI_TRACE=1 rmapi  info`

**Comment by Azeirah** [comment]
> you can run with logging e.g. `RMAPI_TRACE=1 rmapi info`

These are logs:

Trace: 2024/10/30 17:19:06 main.go:72: failed to mirror was not ok: cant parse line '', wrong number of fields 0
ERROR: 2024/10/30 17:19:06 main.go:79: failed to build documents tree, last error: failed to mirror was not ok: cant parse line '', wrong number of fields 0

**Comment by Azeirah** [comment]
The download related to this wasn't available in the log

**Comment by ddvk** [comment]
could you build from source and try again with tracing, or should I push a new version?

**Comment by Azeirah** [comment]
I will try again, I build from source. Thanks!

**Comment by ddvk** [comment]
any feedback?

**Comment by Azeirah** [comment]
Ah, sorry for the delay!

The person who was experiencing the issue reported it was fixed.

**Comment by Azeirah** [comment]
Thank you so much!
